use_frameworks!

platform :ios, '10.0'

target 'ModuloCommons_Example' do
  pod 'ModuloCommons', :path => '../'

  target 'ModuloCommons_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Alamofire', '~> 5.2'
    pod 'AlamofireImage', '~> 4.1'
  end
end
